### ISSUE TITLE
Missing Documentation and Incorrect Output

### ISSUE THREAD

**Issue by DarioS** [ComputationalRegulatoryGenomicsICL/GenomicInteractions#11]
Looking at the code, there are methods like `setMethod("start", "InteractionTrack", function(x) {`, but I don't see them documented.

![image](https://user-images.githubusercontent.com/631218/156701584-abc9e04e-be57-4ab7-ad37-85e747a987b8.png)
 
 Also, the methods don't seem to work correctly.
 
```r
anchor.one <- GRanges(c('chr1', 'chr1', 'chr1', 'chr1'),  IRanges(c(10, 20, 30, 20), width=5))
anchor.two <- GRanges(c('chr1', 'chr1', 'chr1', 'chr2'), IRanges(c(100, 200, 300, 50), width=5))
test <- GenomicInteractions(anchor.one, anchor.two, experiment_name='test', description='this is a test', counts=interaction_counts)
interactions.track <- InteractionTrack(name='Test', test, chromosome='chr1')
> start(interactions.track) # Unexpected output.
NULL
```
If you exported the class to make it visible to the user, surely the accessor functions also need exporting?

**Comment by liz-is** [comment]
Hi, thanks for the question. I didn't write the InteractionTrack code originally and it's been a while since I've looked into it in detail, so please bear with me while I refresh my memory. It seems that you have multiple points: documentation, exporting of the methods, and whether they are working correctly.

InteractionTrack is based on the various Track classes in Gviz and should have the same methods defined. There are start, end, chromosome etc methods defined, but as you say these are not exported (they do seem to be available, though, even if not exported, e.g. `chromosome(interactions.track)` returns the expected output and not a "no method available..." error. I don't know why this happens, it's been too long since I looked into this in detail).

Also, looking at the code, it doesn't look like the code for the start and end methods currently works. I think the intention was for the start and end methods of an InteractionTrack object to return the minimum start coordinate of all anchors (on the chromsome returned by `chromosome()`) and the maximum end coordinate of all anchors (similarly, on the chromsome returned by `chromosome()`). This differs from `start()` or `end()` of a RangeTrack object from Gviz, where they return the start/end coordinates of the ranges corresponding to the track items, i.e. multiple start/end coordinates.

You wrote "`# Unexpected output`" above but I don't know what you expected.  Does the intended result of the current methods (overall start and end coordinates of interactions on the given chromosome) match what you'd expect as a user? Or is your expectation that they would return something more analogous to `start()` or `end()` of a RangeTrack object? The latter is more complex given that interactions involve two anchors. 

I will fix the code and make sure the methods are suitably documented and exported, but since I'm modifying it anyway this is a good opportunity to check what the user expectations actually are.

**Comment by DarioS** [comment]
Thanks for the detailed thoughts. I am not sure about what the function should return, but just not `NULL`.

**Comment by liz-is** [comment]
Hi there, all your comments should be addressed now. The updated version 1.29.3 should also be available through Bioconductor within a few days. I'll close this issue now, but let me know if you have further suggestions and I can reopen it.
