### ISSUE TITLE
Changing curve shape of arcs

### ISSUE THREAD

**Issue by mjko1210** [ComputationalRegulatoryGenomicsICL/GenomicInteractions#7]
Hi,

I also have question if it's possible to change degree of arc curve.

I'm wondering if I can make the curve for trans(blue) as same looking as cis (in red). The angle of blue's arc is almost 90 degree. I wish I can make it look like red ones.

<img width="870" alt="Screen Shot 2020-04-07 at 12 45 16 PM" src="https://user-images.githubusercontent.com/9116362/78712621-bb0c5d80-78cd-11ea-9aa3-1ec3743a578f.png">

Here is my parameters for plotting:

> displayPars(interaction_track) <- list(col.interactions="red", 
> 			                                      col.anchors.fill ="lightblue",
> 			                                      col.anchors.line = "lightblue",
> 			                                      interaction.dimension="height", 
> 			                                      interaction.measure ="counts",
> 			                                      #interaction.dimension.transform = "log",
> 			                                      plot.trans=TRUE,
> 			                                      col.trans = "blue",
> 			                                      plot.outside = TRUE, 
> 			                                      col.outside="red", 
> 			                                      anchor.height = 0.1)

All of my previous questions were actually to make this happen by manipulating data with manual annotation. However, if this is feasible without changing data that would be perfect.

Thanks again!

**Comment by liz-is** [comment]
I had to look back into the plotting code for this, but no, it isn't possible to change the angle of the arc. The angle is determined by the distance between the anchors and the y position of the anchors. For trans interactions, to make it clear that they are not on the same chromosome, we set the y position for the end of the arc to be 0.95 (i.e., 95% relative to the height of the track), whereas for cis interactions, even distant ones, this is set to zero - that's why the left hand red curve in your example has a different shape. 

If you wanted to have a go at modifying the function for your own use, the relevant code is here: https://github.com/ComputationalRegulatoryGenomicsICL/GenomicInteractions/blob/master/R/InteractionTrack-class.R#L234

However I'm not going to make this change in the package, because I think for general use it's important to make a clear visual distinction between cis and trans interactions.
