### ISSUE TITLE
Normalisation in annotateInteractions 

### ISSUE THREAD

**Issue by Rseq** [ComputationalRegulatoryGenomicsICL/GenomicInteractions#9]
Hi again,

I have been working with GenomicInteractions for different datasets.
Some datasets present an enrichment in repetitive elements or other highly abundant regions.
I am interested in knowing if this is related to the biology itself or just an artefact caused by the high amount of those elements in the genome compared to other elements. At the same time, some elements can be occluded by those highly abundant regions in annotateInteractions.
Therefore, I was wondering if it would be possible to normalise the GIObject by the overall annotations in annotateInteractions. 
Is it possible to do so? 

Thank you in advance for your time

**Comment by liz-is** [comment]
Hi there,
I'm not sure I understand what you're thinking of here. Can you give an example of what you mean by "normalisation"? (i.e. what you get now and what you'd hope to get after normalisation)?

**Comment by Rseq** [comment]
Hi,
Thank you again for your reply.
My idea is to see if it is somehow possible to normalise the amounts of interaction that I observe in my dataset with its amount in the genome (or on my custom annotation).

For example, suppose that there are 1550361 LINEs and 402 snoRNA spread over mm10. 

The sum up of annotateInteractions presents something like:
20000 LINE-LINE 
50 snoRNA-snoRNA
120 snoRNA-LINE

By using plotInteractionAnnotations, LINE-LINE will be highlighted because has more counts.
On the other hand, there are way more LINE elements than there are snoRNA in mm10. 
So, I wonder if the interaction can be somehow weighted by the amount available in of its annotations in the mm10 (or any other custom annotation). 
When both ends have the same annotation, it would be possible to have a ratio like
annotation in interaction/ annotation total

20000 LINE-LINE / 1550361 LINE = 0.0129
50 snoRNA-snoRNA / 402 snoRNA = 0.1224

Using something around that ratio would tell me that snoRNA may be more relevant than LINE, which would be highlighted if using only counts.

The problem is when the interaction has ends on different annotations. How one can work around that?
120 snoRNA-LINE 

Would a mean make sense?
120 snoRNA-LINE / (1550361 LINEs + 402 snoRNA / 2)

Please let me know if it is possible to use something around this or it would make sense to adapt it in plotInteractionAnnotations.

Hope I could clarify it better

Best

**Comment by liz-is** [comment]
Hi,

I don't think that this is something that should be implemented in the package, as it's more general rather than being directly linked to interactions, and the calculation to use would be subjective depending on the user / biological question.

However, I can think of a couple of ways you could address this:
* plot a donut/pie chart of the overall prevalence of the annotation features as a reference (you could adapt the code [here](https://github.com/ComputationalRegulatoryGenomicsICL/GenomicInteractions/blob/master/R/plotSummaryStats.R#L139))
* use something like `bedtools shuffle` to randomise the positions of your annotation features, and calculate the % of interactions in each annotation category using the shuffled features (and repeat for many permutations).

Hope that's helpful!
